// ============================================================
// AUTO-GENERATED by generate_clock_themes.py
// ============================================================

#ifndef CLOCK_THEMES_H
#define CLOCK_THEMES_H

#include <Arduino.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>

extern MatrixPanel_I2S_DMA *display;

// Font 5x7 (row bitmasks, MSB=leftmost pixel)
static const uint8_t font5x7[11][7] PROGMEM = {
  { 0b0001110, 0b0010001, 0b0010011, 0b0010101, 0b0011001, 0b0010001, 0b0001110 }, // 0
  { 0b0000100, 0b0001100, 0b0000100, 0b0000100, 0b0000100, 0b0000100, 0b0001110 }, // 1
  { 0b0001110, 0b0010001, 0b0000001, 0b0000010, 0b0000100, 0b0001000, 0b0011111 }, // 2
  { 0b0011110, 0b0000001, 0b0000110, 0b0000001, 0b0000001, 0b0000001, 0b0011110 }, // 3
  { 0b0000010, 0b0000110, 0b0001010, 0b0010010, 0b0011111, 0b0000010, 0b0000010 }, // 4
  { 0b0011111, 0b0010000, 0b0011110, 0b0000001, 0b0000001, 0b0000001, 0b0011110 }, // 5
  { 0b0001110, 0b0010000, 0b0011110, 0b0010001, 0b0010001, 0b0010001, 0b0001110 }, // 6
  { 0b0011111, 0b0000001, 0b0000010, 0b0000100, 0b0000100, 0b0000100, 0b0000100 }, // 7
  { 0b0001110, 0b0010001, 0b0001110, 0b0010001, 0b0010001, 0b0010001, 0b0001110 }, // 8
  { 0b0001110, 0b0010001, 0b0001111, 0b0000001, 0b0000001, 0b0000001, 0b0001110 }, // 9
  { 0b0000000, 0b0000000, 0b0000100, 0b0000000, 0b0000000, 0b0000100, 0b0000000 }, // :
};
static const char font_chars[11] = {'0','1','2','3','4','5','6','7','8','9',':'};

// === MARIO Sprites ===
static const uint16_t mario_mushroom[256] PROGMEM = {
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,
  0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,
  0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,
  0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,
  0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,
  0x0000,0x0000,0xC882,0xF79E,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0xF79E,
  0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,
  0xC882,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,0x7A43,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,
  0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0x0000,
  0x0000,0x0000,0x0000,0x0000
};

static void blit_mario_mushroom(int x, int y) {
  if (x >= 128 || y >= 32 || x + 16 <= 0 || y + 16 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 16 > 128) ? 128 - x : 16;
  int y1 = (y + 16 > 32)  ? 32 - y  : 16;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_mushroom[row*16], 16*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_pipe[192] PROGMEM = {
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,
  0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000,
  0x0000,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x0000
};

static void blit_mario_pipe(int x, int y) {
  if (x >= 128 || y >= 32 || x + 12 <= 0 || y + 16 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 12 > 128) ? 128 - x : 12;
  int y1 = (y + 16 > 32)  ? 32 - y  : 16;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_pipe[row*12], 12*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_small_pipe[96] PROGMEM = {
  0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,0x2504,0x2504,0x2504,
  0x2504,0x2504,0x2504,0x0000,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,
  0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,
  0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,
  0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,0x0000,0x0000,0x2504,0x2504
};

static void blit_mario_small_pipe(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 12 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 12 > 32)  ? 32 - y  : 12;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_small_pipe[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_mario_run0[224] PROGMEM = {
  0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0xC882,0x0000,
  0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,
  0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,
  0x0000,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0x0000,0x0000,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,
  0xFDEF,0x0000,0x0000,0xFDEF,0xFDEF,0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,
  0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,
  0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,
  0x0000,0x0000,0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x7A43,0x7A43,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,
  0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,
  0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
};

static void blit_mario_mario_run0(int x, int y) {
  if (x >= 128 || y >= 32 || x + 14 <= 0 || y + 16 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 14 > 128) ? 128 - x : 14;
  int y1 = (y + 16 > 32)  ? 32 - y  : 16;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_mario_run0[row*14], 14*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_mario_run1[224] PROGMEM = {
  0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0xC882,0x0000,
  0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,
  0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,
  0x0000,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0x0000,0x0000,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,
  0xFDEF,0x0000,0x0000,0xFDEF,0xFDEF,0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,
  0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,
  0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,
  0x0000,0x0000,0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x7A43,0x7A43,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
};

static void blit_mario_mario_run1(int x, int y) {
  if (x >= 128 || y >= 32 || x + 14 <= 0 || y + 16 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 14 > 128) ? 128 - x : 14;
  int y1 = (y + 16 > 32)  ? 32 - y  : 16;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_mario_run1[row*14], 14*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_mario_jump[224] PROGMEM = {
  0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,0xC882,0x0000,
  0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,0x0000,0x0000,
  0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xC882,0xC882,0xC882,0xC882,0xC882,0x0000,
  0x0000,0xC882,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0x0000,0x0000,0xC882,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,0xFDEF,0xFDEF,
  0xFDEF,0xFDEF,0xFDEF,0xFDEF,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xFDEF,
  0xFDEF,0x0000,0x0000,0xFDEF,0xFDEF,0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x2199,0x2199,0x2199,0x2199,
  0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x2199,0x2199,0x0000,0x0000,
  0x2199,0x2199,0x2199,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,
  0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x7A43,0x7A43,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x7A43,0x7A43,0x0000,0x0000,0x7A43,0x7A43,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
};

static void blit_mario_mario_jump(int x, int y) {
  if (x >= 128 || y >= 32 || x + 14 <= 0 || y + 16 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 14 > 128) ? 128 - x : 14;
  int y1 = (y + 16 > 32)  ? 32 - y  : 16;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_mario_jump[row*14], 14*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_cloud[60] PROGMEM = {
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xDEFE,
  0xDEFE,0xDEFE,0xDEFE,0x0000,0x0000,0x0000,0x0000,0x0000,0xDEFE,0xDEFE,0xDEFE,0xDEFE,
  0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0x0000,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,
  0xDEFE,0xDEFE,0xDEFE,0xDEFE,0x0000,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,0xDEFE,
  0xDEFE,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
};

static void blit_mario_cloud(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 6 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 6 > 32)  ? 32 - y  : 6;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_cloud[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_question_block[49] PROGMEM = {
  0x0000,0xFEE4,0xFEE4,0xFEE4,0xFEE4,0xFEE4,0x0000,0xFEE4,0x0000,0x0000,0x0000,0x0000,
  0x0000,0xFEE4,0xFEE4,0x0000,0x0000,0xF79E,0x0000,0x0000,0xFEE4,0xFEE4,0x0000,0x0000,
  0x0000,0x0000,0x0000,0xFEE4,0xFEE4,0x0000,0x0000,0xF79E,0x0000,0x0000,0xFEE4,0xFEE4,
  0x0000,0x0000,0x0000,0x0000,0x0000,0xFEE4,0x0000,0xFEE4,0xFEE4,0xFEE4,0xFEE4,0xFEE4,
  0x0000
};

static void blit_mario_question_block(int x, int y) {
  if (x >= 128 || y >= 32 || x + 7 <= 0 || y + 7 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 7 > 128) ? 128 - x : 7;
  int y1 = (y + 7 > 32)  ? 32 - y  : 7;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_question_block[row*7], 7*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_brick[64] PROGMEM = {
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0x0000,0xB3C7,
  0xB3C7,0x0000,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,
  0xB3C7,0xB3C7,0x0000,0xB3C7,0xB3C7,0x0000,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0x0000,0xB3C7,0xB3C7,0x0000,0xB3C7,0xB3C7,
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0x0000,0xB3C7,
  0xB3C7,0x0000,0xB3C7,0xB3C7
};

static void blit_mario_brick(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_brick[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_ground[32] PROGMEM = {
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,
  0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7,0xB3C7
};

static void blit_mario_ground(int x, int y) {
  if (x >= 128 || y >= 32 || x + 16 <= 0 || y + 2 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 16 > 128) ? 128 - x : 16;
  int y1 = (y + 2 > 32)  ? 32 - y  : 2;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_ground[row*16], 16*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t mario_bush[24] PROGMEM = {
  0x0000,0x0000,0x2504,0x2504,0x2504,0x2504,0x0000,0x0000,0x0000,0x2504,0x2504,0x2504,
  0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504,0x2504
};

static void blit_mario_bush(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &mario_bush[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}

// === TETRIS Sprites ===
static const uint16_t tetris_piece_I[16] PROGMEM = {
  0x0000,0x0000,0x0000,0x0000,0x07FF,0x07FF,0x07FF,0x07FF,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_I(int x, int y) {
  if (x >= 128 || y >= 32 || x + 4 <= 0 || y + 4 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 4 > 128) ? 128 - x : 4;
  int y1 = (y + 4 > 32)  ? 32 - y  : 4;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_I[row*4], 4*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_O[4] PROGMEM = {
  0xFFE0,0xFFE0,0xFFE0,0xFFE0
};

static void blit_tetris_piece_O(int x, int y) {
  if (x >= 128 || y >= 32 || x + 2 <= 0 || y + 2 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 2 > 128) ? 128 - x : 2;
  int y1 = (y + 2 > 32)  ? 32 - y  : 2;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_O[row*2], 2*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_T[9] PROGMEM = {
  0xB01F,0xB01F,0xB01F,0x0000,0xB01F,0x0000,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_T(int x, int y) {
  if (x >= 128 || y >= 32 || x + 3 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 3 > 128) ? 128 - x : 3;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_T[row*3], 3*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_S[9] PROGMEM = {
  0x0000,0x06E0,0x06E0,0x06E0,0x06E0,0x0000,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_S(int x, int y) {
  if (x >= 128 || y >= 32 || x + 3 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 3 > 128) ? 128 - x : 3;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_S[row*3], 3*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_Z[9] PROGMEM = {
  0xD800,0xD800,0x0000,0x0000,0xD800,0xD800,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_Z(int x, int y) {
  if (x >= 128 || y >= 32 || x + 3 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 3 > 128) ? 128 - x : 3;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_Z[row*3], 3*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_J[9] PROGMEM = {
  0x029F,0x0000,0x0000,0x029F,0x029F,0x029F,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_J(int x, int y) {
  if (x >= 128 || y >= 32 || x + 3 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 3 > 128) ? 128 - x : 3;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_J[row*3], 3*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t tetris_piece_L[9] PROGMEM = {
  0x0000,0x0000,0xFD00,0xFD00,0xFD00,0xFD00,0x0000,0x0000,0x0000
};

static void blit_tetris_piece_L(int x, int y) {
  if (x >= 128 || y >= 32 || x + 3 <= 0 || y + 3 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 3 > 128) ? 128 - x : 3;
  int y1 = (y + 3 > 32)  ? 32 - y  : 3;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &tetris_piece_L[row*3], 3*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}

// === PAC Sprites ===
static const uint16_t pac_pacman1[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0x0000,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman1(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman1[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman2[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman2(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman2[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman3[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman3(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman3[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_ghost_red[64] PROGMEM = {
  0x0000,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0x0000,0xF800,0xF800,0xF800,0xF800,
  0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF79E,0xF79E,0xF79E,0xF800,0xF800,0xF800,
  0xF800,0xF800,0xF800,0x0019,0x0019,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,
  0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,0xF800,
  0xF800,0xF800,0x0000,0xF800,0xF800,0x0000,0xF800,0xF800,0xF800,0x0000,0x0000,0xF800,
  0x0000,0x0000,0xF800,0xF800
};

static void blit_pac_ghost_red(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_ghost_red[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_ghost_pink[72] PROGMEM = {
  0x0000,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0x0000,0xFBD9,0xFBD9,0xFBD9,
  0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xF79E,0xF79E,0xF79E,0xFBD9,0xFBD9,
  0xFBD9,0xFBD9,0xFBD9,0xFBD9,0x0019,0x0019,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,
  0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,0xFBD9,
  0xFBD9,0xFBD9,0xFBD9,0x0000,0xFBD9,0xFBD9,0x0000,0xFBD9,0xFBD9,0xFBD9,0x0000,0x0000,
  0xFBD9,0x0000,0x0000,0xFBD9,0xFBD9
};

static void blit_pac_ghost_pink(int x, int y) {
  if (x >= 128 || y >= 32 || x + 9 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 9 > 128) ? 128 - x : 9;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_ghost_pink[row*9], 9*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pellet[4] PROGMEM = {
  0x0000,0x0000,0x0000,0x0000
};

static void blit_pac_pellet(int x, int y) {
  if (x >= 128 || y >= 32 || x + 2 <= 0 || y + 2 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 2 > 128) ? 128 - x : 2;
  int y1 = (y + 2 > 32)  ? 32 - y  : 2;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pellet[row*2], 2*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_ghost_cyan[64] PROGMEM = {
  0x0000,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x0000,0x065F,0x065F,0x065F,0x065F,
  0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0xF79E,0xF79E,0xF79E,0x065F,0x065F,0x065F,
  0x065F,0x065F,0x065F,0x0019,0x0019,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,
  0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,0x065F,
  0x065F,0x065F,0x0000,0x065F,0x065F,0x0000,0x065F,0x065F,0x065F,0x0000,0x0000,0x065F,
  0x0000,0x0000,0x065F,0x065F
};

static void blit_pac_ghost_cyan(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_ghost_cyan[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_ghost_orange[64] PROGMEM = {
  0x0000,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0x0000,0xFD07,0xFD07,0xFD07,0xFD07,
  0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xF79E,0xF79E,0xF79E,0xFD07,0xFD07,0xFD07,
  0xFD07,0xFD07,0xFD07,0x0019,0x0019,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,
  0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,0xFD07,
  0xFD07,0xFD07,0x0000,0xFD07,0xFD07,0x0000,0xFD07,0xFD07,0xFD07,0x0000,0x0000,0xFD07,
  0x0000,0x0000,0xFD07,0xFD07
};

static void blit_pac_ghost_orange(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_ghost_orange[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_wall_h[4] PROGMEM = {
  0x2959,0x2959,0x2959,0x2959
};

static void blit_pac_wall_h(int x, int y) {
  if (x >= 128 || y >= 32 || x + 4 <= 0 || y + 1 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 4 > 128) ? 128 - x : 4;
  int y1 = (y + 1 > 32)  ? 32 - y  : 1;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_wall_h[row*4], 4*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman1_down[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0x0000,
  0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,
  0x0000,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman1_down(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman1_down[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman1_left[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman1_left(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman1_left[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman1_up[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0x0000,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman1_up(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman1_up[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman2_down[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0x0000,
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,
  0x0000,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman2_down(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman2_down[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman2_left[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman2_left(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman2_left[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman2_up[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,0x0000,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman2_up(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman2_up[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman3_down[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman3_down(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman3_down[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman3_left[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman3_left(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman3_left[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t pac_pacman3_up[100] PROGMEM = {
  0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0xFEE0,0xFEE0,0xFEE0,0x0000,0x0000,0x0000,0xFEE0,0xFEE0,0xFEE0,0xFEE0,
  0xFEE0,0xFEE0,0x0000,0x0000
};

static void blit_pac_pacman3_up(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 10 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 10 > 32)  ? 32 - y  : 10;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &pac_pacman3_up[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}

// === INV Sprites ===
static const uint16_t inv_crab_0[88] PROGMEM = {
  0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,
  0x0000,0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,0x06E0,
  0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,0x06E0,0x06E0,0x0000,0x06E0,0x0000,0x06E0,
  0x0000,0x06E0,0x0000,0x06E0,0x06E0,0x06E0,0x0000,0x0000,0x06E0,0x06E0,0x0000,0x06E0,
  0x06E0,0x0000,0x0000,0x06E0
};

static void blit_inv_crab_0(int x, int y) {
  if (x >= 128 || y >= 32 || x + 11 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 11 > 128) ? 128 - x : 11;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_crab_0[row*11], 11*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_crab_1[88] PROGMEM = {
  0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,
  0x0000,0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x0000,0x0000,0x0000,0x06E0,
  0x06E0,0x0000,0x0000,0x0000,0x0000,0x0000,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,0x06E0,
  0x06E0,0x06E0,0x06E0,0x06E0,0x0000,0x06E0,0x06E0,0x0000,0x06E0,0x0000,0x06E0,0x0000,
  0x06E0,0x0000,0x06E0,0x0000,0x06E0,0x06E0,0x0000,0x0000,0x06E0,0x06E0,0x0000,0x06E0,
  0x06E0,0x0000,0x0000,0x06E0
};

static void blit_inv_crab_1(int x, int y) {
  if (x >= 128 || y >= 32 || x + 11 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 11 > 128) ? 128 - x : 11;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_crab_1[row*11], 11*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_octopus_0[80] PROGMEM = {
  0x0000,0x0000,0x0000,0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0x0000,0x0000,
  0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0x0000,0xD800,0xD800,
  0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0xD800,0xD800,0xD800,0xD800,0xD800,
  0xD800,0xD800,0xD800,0x0000,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,
  0xD800,0xD800,0xD800,0x0000,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0x0000,0xD800,
  0xD800,0xD800,0x0000,0x0000,0xD800,0xD800,0x0000,0x0000,0xD800,0xD800,0x0000,0xD800,
  0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xD800,0x0000
};

static void blit_inv_octopus_0(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_octopus_0[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_octopus_1[80] PROGMEM = {
  0x0000,0x0000,0x0000,0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0x0000,0x0000,
  0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0x0000,0xD800,0xD800,
  0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0x0000,0xD800,0xD800,0xD800,0xD800,0xD800,
  0xD800,0xD800,0xD800,0x0000,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,0xD800,
  0xD800,0xD800,0xD800,0xD800,0x0000,0x0000,0xD800,0xD800,0x0000,0x0000,0xD800,0xD800,
  0xD800,0x0000,0xD800,0x0000,0x0000,0x0000,0x0000,0xD800,0x0000,0xD800,0x0000,0xD800,
  0xD800,0x0000,0x0000,0x0000,0x0000,0xD800,0xD800,0x0000
};

static void blit_inv_octopus_1(int x, int y) {
  if (x >= 128 || y >= 32 || x + 10 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 10 > 128) ? 128 - x : 10;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_octopus_1[row*10], 10*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_squid_0[64] PROGMEM = {
  0x0000,0x0000,0x0000,0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0x0000,0x0000,0xDEE0,0xDEE0,
  0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0x0000,
  0x0000,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0x0000,0x0000,0xDEE0,0xDEE0,0xDEE0,
  0xDEE0,0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0x0000,0x0000,0xDEE0,0x0000,0x0000,
  0x0000,0x0000,0xDEE0,0x0000,0x0000,0xDEE0,0x0000,0x0000,0x0000,0x0000,0xDEE0,0x0000,
  0x0000,0xDEE0,0x0000,0x0000
};

static void blit_inv_squid_0(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_squid_0[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_squid_1[64] PROGMEM = {
  0x0000,0x0000,0x0000,0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0x0000,0x0000,0xDEE0,0xDEE0,
  0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0x0000,
  0x0000,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0xDEE0,0x0000,0x0000,0xDEE0,0xDEE0,0xDEE0,
  0xDEE0,0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0x0000,0x0000,0xDEE0,0x0000,0x0000,
  0x0000,0xDEE0,0xDEE0,0x0000,0x0000,0xDEE0,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0x0000,
  0x0000,0xDEE0,0x0000,0x0000
};

static void blit_inv_squid_1(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 8 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 8 > 32)  ? 32 - y  : 8;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_squid_1[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_ship[77] PROGMEM = {
  0x0000,0x0000,0x0000,0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0x0000,0x0000,0xF79E,0xF79E,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,
  0x0000,0xF79E,0xF79E,0xF79E,0xF79E,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0xF79E,
  0xF79E,0xF79E,0xF79E,0xF79E,0xF79E,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0xF79E,
  0xF79E,0xF79E,0xF79E,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xF79E,
  0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000,0xF79E,0x0000,0x0000,
  0x0000,0xF79E,0x0000,0x0000,0x0000
};

static void blit_inv_ship(int x, int y) {
  if (x >= 128 || y >= 32 || x + 11 <= 0 || y + 7 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 11 > 128) ? 128 - x : 11;
  int y1 = (y + 7 > 32)  ? 32 - y  : 7;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_ship[row*11], 11*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_saucer[48] PROGMEM = {
  0x0000,0x0000,0xD81B,0xD81B,0xD81B,0xD81B,0x0000,0x0000,0x0000,0xD81B,0xD81B,0xD81B,
  0xD81B,0xD81B,0xD81B,0x0000,0xD81B,0xD81B,0xD81B,0xD81B,0xD81B,0xD81B,0xD81B,0xD81B,
  0xD81B,0x0000,0x0000,0xD81B,0xD81B,0x0000,0x0000,0xD81B,0x0000,0xD81B,0x0000,0x0000,
  0x0000,0x0000,0xD81B,0x0000,0x0000,0x0000,0xD81B,0x0000,0x0000,0xD81B,0x0000,0x0000
};

static void blit_inv_saucer(int x, int y) {
  if (x >= 128 || y >= 32 || x + 8 <= 0 || y + 6 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 8 > 128) ? 128 - x : 8;
  int y1 = (y + 6 > 32)  ? 32 - y  : 6;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_saucer[row*8], 8*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_missile[30] PROGMEM = {
  0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0x0000,0xF79E,0x0000,0x0000,0x0000,0xF79E,
  0xF79E,0xF79E,0x0000,0x0000,0xF79E,0xF79E,0xF79E,0x0000,0x0000,0x0000,0xF79E,0x0000,
  0x0000,0x0000,0x0000,0xF79E,0x0000,0x0000
};

static void blit_inv_missile(int x, int y) {
  if (x >= 128 || y >= 32 || x + 5 <= 0 || y + 6 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 5 > 128) ? 128 - x : 5;
  int y1 = (y + 6 > 32)  ? 32 - y  : 6;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_missile[row*5], 5*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}
static const uint16_t inv_explosion[25] PROGMEM = {
  0x0000,0xDEE0,0x0000,0xDEE0,0x0000,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0x0000,0x0000,
  0xDEE0,0x0000,0x0000,0xDEE0,0x0000,0x0000,0x0000,0xDEE0,0x0000,0xDEE0,0x0000,0xDEE0,
  0x0000
};

static void blit_inv_explosion(int x, int y) {
  if (x >= 128 || y >= 32 || x + 5 <= 0 || y + 5 <= 0) return;
  int x0 = (x < 0) ? -x : 0;
  int y0 = (y < 0) ? -y : 0;
  int x1 = (x + 5 > 128) ? 128 - x : 5;
  int y1 = (y + 5 > 32)  ? 32 - y  : 5;
  static uint16_t rowbuf[16];
  for (int row = y0; row < y1; row++) {
    memcpy_P(rowbuf, &inv_explosion[row*5], 5*2);
    int dy = y + row;
    for (int col = x0; col < x1; col++) {
      uint16_t c = rowbuf[col];
      if (c) display->drawPixel(x + col, dy, c);
    }
  }
}


// ── Helpers ─────────────────────────────────────────────────
// Integer sine table (8-bit, -127..127), avoids sinf() crashes
static const int8_t sin8[256] = { 0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,59,62,65,67,70,73,75,78,80,82,85,87,89,91,94,96,98,100,102,103,105,107,108,110,112,113,114,116,117,118,119,120,121,122,123,123,124,125,125,126,126,126,126,126,127,126,126,126,126,126,125,125,124,123,123,122,121,120,119,118,117,116,114,113,112,110,108,107,105,103,102,100,98,96,94,91,89,87,85,82,80,78,75,73,70,67,65,62,59,57,54,51,48,45,42,39,36,33,30,27,24,21,18,15,12,9,6,3,0,-3,-6,-9,-12,-15,-18,-21,-24,-27,-30,-33,-36,-39,-42,-45,-48,-51,-54,-57,-59,-62,-65,-67,-70,-73,-75,-78,-80,-82,-85,-87,-89,-91,-94,-96,-98,-100,-102,-103,-105,-107,-108,-110,-112,-113,-114,-116,-117,-118,-119,-120,-121,-122,-123,-123,-124,-125,-125,-126,-126,-126,-126,-126,-127,-126,-126,-126,-126,-126,-125,-125,-124,-123,-123,-122,-121,-120,-119,-118,-117,-116,-114,-113,-112,-110,-108,-107,-105,-103,-102,-100,-98,-96,-94,-91,-89,-87,-85,-82,-80,-78,-75,-73,-70,-67,-65,-62,-59,-57,-54,-51,-48,-45,-42,-39,-36,-33,-30,-27,-24,-21,-18,-15,-12,-9,-6,-3 };
#define sin8_ms(ms, period)  sin8[((ms) / (period)) % 256]

// Color565 helper (inlined for speed)
static uint16_t c565(uint8_t r, uint8_t g, uint8_t b) {
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

// Draw a 5x7 font character at (x,y) using direct pixel drawing
static void drawFontChar(int x, int y, char ch, uint16_t color) {
  int idx = -1;
  for (int i = 0; i < 11; i++) { if (font_chars[i] == ch) { idx = i; break; } }
  if (idx < 0) return;
  uint8_t rows[7];
  memcpy_P(rows, font5x7[idx], 7);
  for (int row = 0; row < 7; row++) {
    for (int col = 0; col < 5; col++) {
      if (rows[row] & (0x10 >> col))
        display->drawPixel(x+col, y+row, color);
    }
  }
}

// Draw a 5x7 font character at 4x scale (each pixel becomes a 4x4 block = 20x28 px)
// Used by large-digit artistic themes (Neon, Matrix, Fire, Rainbow)
static void drawLargeFontChar(int x, int y, char ch, uint16_t color) {
  int idx = -1;
  for (int i = 0; i < 11; i++) { if (font_chars[i] == ch) { idx = i; break; } }
  if (idx < 0) return;
  uint8_t rows[7];
  memcpy_P(rows, font5x7[idx], 7);
  for (int row = 0; row < 7; row++) {
    for (int col = 0; col < 5; col++) {
      if (rows[row] & (0x10 >> col))
        display->fillRect(x + col*4, y + row*4, 4, 4, color);
    }
  }
}

static void drawTimeHHMM(int x, int y, int h, int m, uint16_t color) {
  char buf[5];
  buf[0] = '0' + h/10; buf[1] = '0' + h%10; buf[2] = ':';
  buf[3] = '0' + m/10; buf[4] = '0' + m%10;
  for (int i = 0; i < 5; i++) drawFontChar(x + i*6, y, buf[i], color);
}

// ── THEME 1: SUPER MARIO ────────────────────
// Mario runs across screen with proper running animation
static void drawTheme_Mario(int h, int m, int s, unsigned long ms) {
  uint16_t sky = c565(40,80,180);
  display->fillRect(0, 0, 128, 32, sky);
  display->fillRect(0, 26, 128, 6, c565(80,50,20));
  display->fillRect(0, 25, 128, 1, c565(100,70,30));
  int cx1 = 128 - (ms / 80) % 200;
  int cx2 = 128 - (ms / 110 + 70) % 200;
  int cx3 = 128 - (ms / 60 + 140) % 200;
  blit_mario_cloud(cx1, 1); blit_mario_cloud(cx2, 4); blit_mario_cloud(cx3, 2);
  int qbPhase = (ms / 25) % 256;
  int qb1=0, qb2=0;
  if (qbPhase < 15) qb1 = (15 - qbPhase) / 2;
  if (((qbPhase+85)%256) < 15) qb2 = (15 - (qbPhase+85)%256) / 2;
  blit_mario_question_block(20, 2 - qb1);
  blit_mario_question_block(90, 2 - qb2);
  blit_mario_brick(44, 16); blit_mario_brick(52, 16);
  blit_mario_brick(72, 16); blit_mario_brick(80, 16);
  // Pipes on ground - cycling which 2 of 3 appear
  int pipePhase = (ms / 500) % 3;
  int hideX = pipePhase == 0 ? 8 : pipePhase == 1 ? 56 : 108;
  if (hideX != 8) blit_mario_pipe(8, 10);
  if (hideX != 56) blit_mario_pipe(56, 10);
  if (hideX != 108) blit_mario_pipe(108, 10);
  // Mushroom near first ? block, bouncing with sine
  int mushBounce = sin8_ms(ms, 600);
  if (mushBounce < 0) mushBounce = -mushBounce;
  int my = 10 - mushBounce / 25;
  blit_mario_mushroom(22, my);
  // Small decorative pipe on ground
  blit_mario_small_pipe(120, 14);
  int mx = (ms / 20) % (128 + 18) - 18;
  int mf = (ms / 120) % 2;
  if (mf == 0) blit_mario_mario_run0(mx, 10);
  else blit_mario_mario_run1(mx, 10);
  drawTimeHHMM(45, 25, h, m, c565(255,255,255));
}
// ── THEME 2: TETRIS ─────────────────────────
// Big blocks (4x4), vertical pieces, stacking at bottom
// Each piece is drawn as 4x4 pixel blocks with 1px gap
#define TETRIS_COLS 10
#define TETRIS_ROWS 8
static uint8_t tetrisGrid[TETRIS_ROWS][TETRIS_COLS];

static void tetrisGridClear() {
  for (int r = 0; r < TETRIS_ROWS; r++)
    for (int c = 0; c < TETRIS_COLS; c++)
      tetrisGrid[r][c] = 0xFF;
}

static void tetrisDrawBlock(int x, int y, uint16_t color) {
  display->fillRect(x, y, 4, 4, color);
  display->drawPixel(x+1, y+0, 0xFFFF); // highlight
  display->drawPixel(x+0, y+1, 0xFFFF);
  display->drawPixel(x+3, y+2, 0x0000); // shadow
  display->drawPixel(x+2, y+3, 0x0000);
}

static void drawTheme_Tetris(int h, int m, int s, unsigned long ms) {
  static bool gridInit = false;
  if (!gridInit) { tetrisGridClear(); gridInit = true; }
  display->fillRect(0, 0, 128, 32, c565(0,0,20));

  // Pending pieces animation on the left
  uint16_t pieceColors[7] = { c565(0,255,255), c565(255,255,0), c565(180,0,255),
    c565(0,220,0), c565(220,0,0), c565(0,80,255), c565(255,160,0) };
  // Piece shapes: each is bitmask 4x4 (bits MSB=leftmost)
  const uint8_t tShapes[7][4] = {
    {0x8, 0x8, 0x8, 0x8}, // I: vertical line PW=1
    {0xC, 0xC, 0, 0},     // O: 2x2 square PW=2
    {0xE, 0x4, 0, 0},     // T: row0=111 row1=010 PW=3
    {0x6, 0xC, 0, 0},     // S: row0=011 row1=110 PW=3
    {0xC, 0x6, 0, 0},     // Z: row0=110 row1=011 PW=3
    {0x8, 0xE, 0, 0},     // J: row0=100 row1=111 PW=3
    {0x2, 0xE, 0, 0},     // L: row0=001 row1=111 PW=3
  };
  static const int tPW[7] = {1, 2, 3, 3, 3, 3, 3};

  // Persistent falling piece state
  static int tPiece = -1;
  static int tCol = 0;
  static int tRow = 0;
  static unsigned long tLastMs = 0;

  if (tPiece < 0) {
    tPiece = random(0, 7);
    tCol = random(0, TETRIS_COLS - tPW[tPiece] + 1);
    tRow = 0;
    tLastMs = ms;
  }

  bool lockPiece = false;

  if (ms - tLastMs >= 600) {
    int nextRow = tRow + 1;
    bool canGoDown = true;
    for (int r = 3; r >= 0 && canGoDown; r--)
      if (tShapes[tPiece][r] && nextRow + r >= TETRIS_ROWS) canGoDown = false;
    if (canGoDown) {
      for (int r = 0; r < 4; r++) {
        if (!tShapes[tPiece][r]) continue;
        int gr = nextRow + r;
        if (gr >= TETRIS_ROWS) break;
        for (int c = 0; c < tPW[tPiece]; c++)
          if (tShapes[tPiece][r] & (1 << (3-c)))
            if (tetrisGrid[gr][tCol+c] != 0xFF) { canGoDown = false; break; }
        if (!canGoDown) break;
      }
    }
    if (canGoDown) tRow = nextRow;
    else lockPiece = true;
    tLastMs = ms;
  }

  if (!lockPiece) {
    for (int r = 0; r < 4 && tRow+r < TETRIS_ROWS; r++) {
      if (!tShapes[tPiece][r]) continue;
      for (int c = 0; c < tPW[tPiece]; c++)
        if (tShapes[tPiece][r] & (1 << (3-c)))
          if (tetrisGrid[tRow+r][tCol+c] != 0xFF) { lockPiece = true; break; }
      if (lockPiece) break;
    }
  }

  if (lockPiece) {
    bool gameOver = false;
    for (int r = 0; r < 4 && tRow+r < TETRIS_ROWS; r++) {
      if (!tShapes[tPiece][r]) continue;
      for (int c = 0; c < tPW[tPiece]; c++) {
        if (tShapes[tPiece][r] & (1 << (3-c))) {
          if (tetrisGrid[tRow+r][tCol+c] != 0xFF) gameOver = true;
          else tetrisGrid[tRow+r][tCol+c] = tPiece;
        }
      }
    }
    if (gameOver) {
      tetrisGridClear();
    } else {
      for (int r = TETRIS_ROWS-1; r >= 0; r--) {
        bool full = true;
        for (int c = 0; c < TETRIS_COLS; c++)
          if (tetrisGrid[r][c] == 0xFF) { full = false; break; }
        if (full) {
          for (int r2 = r; r2 > 0; r2--)
            for (int c2 = 0; c2 < TETRIS_COLS; c2++)
              tetrisGrid[r2][c2] = tetrisGrid[r2-1][c2];
          for (int c2 = 0; c2 < TETRIS_COLS; c2++)
            tetrisGrid[0][c2] = 0xFF;
          r++;
        }
      }
    }
    tPiece = -1;
  }

  // Draw accumulated pieces from grid
  for (int r = 0; r < TETRIS_ROWS; r++) {
    for (int c = 0; c < TETRIS_COLS; c++) {
      if (tetrisGrid[r][c] != 0xFF)
        tetrisDrawBlock(4 + c*5, r*4, pieceColors[tetrisGrid[r][c]]);
    }
  }

  // Playfield border frame
  display->drawRect(3, 0, 51, 32, c565(60,60,100));

  // Draw falling piece
  if (tPiece >= 0) {
    for (int br = 0; br < 4 && tRow+br < TETRIS_ROWS; br++) {
      for (int bc = 0; bc < tPW[tPiece]; bc++) {
        if (tShapes[tPiece][br] & (1 << (3-bc))) {
          int px = 4 + (tCol+bc)*5;
          int py = (tRow+br)*4;
          tetrisDrawBlock(px, py, pieceColors[tPiece]);
        }
      }
    }
  }

  // Simple buildings above score panel (St. Basil style)
  uint16_t gold = c565(210,190,60);
  display->fillRect(88, 4, 12, 7, c565(150,30,30));
  display->fillRect(90, 2, 8, 2, gold);
  display->drawPixel(92, 1, gold); display->drawPixel(93, 1, gold);
  display->fillRect(104, 3, 10, 8, c565(30,100,30));
  display->fillRect(106, 1, 6, 2, gold);
  display->drawPixel(108, 0, gold); display->drawPixel(109, 0, gold);
  display->fillRect(118, 5, 8, 6, c565(30,30,150));
  display->fillRect(120, 3, 4, 2, gold);
  display->drawPixel(121, 2, gold); display->drawPixel(122, 2, gold);

  // Score box outline
  display->drawRect(84, 10, 42, 20, c565(60,60,100));
  // Time display in score box
  uint16_t tc = pieceColors[(h+m+ms/200) % 7];
  char buf[5];
  buf[0] = '0'+h/10; buf[1] = '0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  for (int i = 0; i < 5; i++) {
    if (i == 2 && (ms/1000)%2 == 0) continue;
    drawFontChar(91 + i*6, 17, buf[i], tc);
  }
}

// ── THEME 3: PAC-MAN ────────────────────────
// Yellow pellet path around screen, Pac-Man & ghost follow path
static void drawTheme_Pacman(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));
  uint16_t dot = c565(255,200,100);
  uint16_t bigDot = c565(255,220,0);
  int totalDots = 84;
  int pathX[84], pathY[84];
  // Top: left to right (24 dots, 5px apart)
  for (int i = 0; i < 24; i++) { pathX[i] = 4 + i*5; pathY[i] = 5; }
  // Right: top to bottom (6 dots, 4px apart, stays on-screen)
  for (int i = 24; i < 30; i++) { pathX[i] = 124; pathY[i] = 6 + (i-24)*4; }
  // Bottom: right to left (24 dots, 5px apart)
  for (int i = 30; i < 54; i++) { pathX[i] = 119 - (i-30)*5; pathY[i] = 26; }
  // Left: bottom to top (6 dots, 4px apart)
  for (int i = 54; i < 60; i++) { pathX[i] = 4; pathY[i] = 25 - (i-54)*4; }
  // Close: return to start (24 dots, 5px apart)
  for (int i = 60; i < 84; i++) { pathX[i] = 9 + (i-60)*5; pathY[i] = 5; }
  // Big dots at the 4 corners
   int corners[4][2] = {{4, 5}, {124, 5}, {124, 26}, {4, 26}};
  for (int i = 0; i < 4; i++) {
    display->fillRect(corners[i][0]-2, corners[i][1]-2, 5, 5, bigDot);
  }
  // Draw path dots
  for (int i = 0; i < totalDots; i++) {
    display->drawPixel(pathX[i], pathY[i], dot);
  }
  int pacIdx = (ms / 100) % totalDots;
  int pacFrame = (ms / 200) % 3;
  int px = pathX[pacIdx], py = pathY[pacIdx];
  int dir = 0;
  if (pacIdx >= 0 && pacIdx < 24) dir = 0;
  else if (pacIdx >= 24 && pacIdx < 30) dir = 1;
  else if (pacIdx >= 30 && pacIdx < 54) dir = 2;
  else if (pacIdx >= 54 && pacIdx < 60) dir = 3;
  else dir = 0;
  if (dir == 0) {
    if (pacFrame == 0) blit_pac_pacman1(px-5, py-5);
    else if (pacFrame == 1) blit_pac_pacman2(px-5, py-5);
    else blit_pac_pacman3(px-5, py-5);
  } else if (dir == 1) {
    if (pacFrame == 0) blit_pac_pacman1_down(px-5, py-5);
    else if (pacFrame == 1) blit_pac_pacman2_down(px-5, py-5);
    else blit_pac_pacman3_down(px-5, py-5);
  } else if (dir == 2) {
    if (pacFrame == 0) blit_pac_pacman1_left(px-5, py-5);
    else if (pacFrame == 1) blit_pac_pacman2_left(px-5, py-5);
    else blit_pac_pacman3_left(px-5, py-5);
  } else {
    if (pacFrame == 0) blit_pac_pacman1_up(px-5, py-5);
    else if (pacFrame == 1) blit_pac_pacman2_up(px-5, py-5);
    else blit_pac_pacman3_up(px-5, py-5);
  }
  int ghostOffsets[4] = {8, 14, 22, 30};
  for (int g = 0; g < 4; g++) {
    int ghostIdx = (pacIdx - ghostOffsets[g] + totalDots) % totalDots;
    int gx = pathX[ghostIdx]-4, gy = pathY[ghostIdx]-4;
    if (g == 0) blit_pac_ghost_red(gx, gy);
    else if (g == 1) blit_pac_ghost_pink(gx, gy);
    else if (g == 2) blit_pac_ghost_cyan(gx, gy);
    else blit_pac_ghost_orange(gx, gy);
  }
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  uint16_t yellow = c565(255,220,0);
  for (int i = 0; i < 5; i++) drawFontChar(49 + i*6, 12, buf[i], yellow);
}
// ── THEME 4: SPACE INVADERS ──────────────────
static void drawTheme_Invaders(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));

  // Marching Space Invaders - ping-pong animation
  int marchPhase = (ms / 80) % 24;
  int marchX = marchPhase < 12 ? marchPhase : 23 - marchPhase;
  int invFrame = (ms / 400) % 2;

  // 6 invaders per row, tighter 18px spacing
  int nCol = 6;
  int startX = 15;

  // Row 0: Squid (8x8, top row)
  for (int col = 0; col < nCol; col++) {
    int ix = startX + col*18 + marchX;
    if (ix > -10 && ix < 128) {
      if (invFrame==0) blit_inv_squid_0(ix, 0);
      else blit_inv_squid_1(ix, 0);
    }
  }

  // Row 1: Octopus (11x8, middle row)
  for (int col = 0; col < nCol; col++) {
    int ix = startX + col*18 + marchX;
    if (ix > -12 && ix < 128) {
      if (invFrame==0) blit_inv_octopus_0(ix, 7);
      else blit_inv_octopus_1(ix, 7);
    }
  }

  // Row 2: Crab (11x8, bottom row)
  for (int col = 0; col < nCol; col++) {
    int ix = startX + col*18 + marchX;
    if (ix > -12 && ix < 128) {
      if (invFrame==0) blit_inv_crab_0(ix, 14);
      else blit_inv_crab_1(ix, 14);
    }
  }

  // Ship (player cannon)
  int shipX = 64 + (sin8_ms(ms, 50) * 20 / 127);
  blit_inv_ship(shipX, 25);

  // Saucer (mystery ship at top, every ~5s)
  int saucerPeriod = 5000;
  int saucerMs = ms % saucerPeriod;
  if (saucerMs < 1800) {
    int saucerX = (saucerMs * 140) / 1800 - 10;
    blit_inv_saucer(saucerX, 0);
  }

  // Missile fired from ship
  int shotMs = ms % 1200;
  if (shotMs < 600) {
    int bulletY = 24 - (shotMs * 24 / 600);
    if (bulletY < 0) bulletY = 0;
    blit_inv_missile(shipX+4, bulletY);
  }

  // Time split on each side of ship
  uint16_t sc = (ms/150)%2 ? c565(0,255,0) : c565(255,255,0);
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  // Hours on the left
  drawFontChar(15, 22, buf[0], sc);
  drawFontChar(24, 22, buf[1], sc);
  // Colon blinking in center area
  if ((ms/1000)%2) drawFontChar(62, 22, ':', sc);
  // Minutes on the right
  drawFontChar(98, 22, buf[3], sc);
  drawFontChar(107, 22, buf[4], sc);
}

// ── THEME 9: PONG (SCORE CLOCK) ──────────────
// Ball bounces between paddles, digits are the score display.
static void drawTheme_Pong(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));

  // Center dashed line
  for (int y = 0; y < 32; y += 4)
    display->drawPixel(64, y, c565(60,60,60));

  // Paddles (auto-play)
  uint16_t paddleCol = c565(200,200,200);
  int paddleH = 8;
  int leftY  = 10 + (sin8[(ms/15) % 256] * 8 / 127);
  int rightY = 10 + (sin8[(ms/12 + 80) % 256] * 8 / 127);
  display->fillRect(2, leftY, 2, paddleH, paddleCol);
  display->fillRect(124, rightY, 2, paddleH, paddleCol);

  // Ball bouncing
  int ballPhase = (ms / 12) % 256;
  int ballXoff = sin8[ballPhase] * 56 / 127;
  int ballYoff = sin8[(ballPhase + 64) % 256] * 12 / 127;
  int bx = 64 + ballXoff;
  int by = 14 + ballYoff;
  if (by < 2) by = 2;
  if (by > 28) by = 28;
  display->fillRect(bx-1, by-1, 3, 3, c565(200,200,200));

  // Clock digits as score (HH:MM centered)
  uint16_t scoreCol = c565(255,180,0);
  char buf[5];
  buf[0] = '0'+h/10; buf[1] = '0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;

  // Centered evenly: each char at 12px spacing, colon centered on x=64
  const uint8_t px[5] = {40, 52, 62, 76, 88};
  for (int i = 0; i < 5; i++) {
    if (i == 2) { if ((ms/1000)%2) drawFontChar(px[i], 8, buf[i], scoreCol); }
    else drawFontChar(px[i], 8, buf[i], scoreCol);
  }

  // Score underline
  display->drawRect(36, 16, 56, 1, c565(80,60,0));
}

// ── THEME 5: NEON ──────────────────────────
// Large glowing neon tube digits (pink + blue, pulsing)
static void drawTheme_Neon(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));
  int pulse = (sin8_ms(ms, 120) + 128) * 200 / 255;
  uint16_t pink = c565(255, 40, 120);
  uint16_t blue = c565(40, 200, 255);
  uint16_t pinkGlow = c565(pulse*160/255, pulse*25/255, pulse*75/255);
  uint16_t blueGlow = c565(pulse*25/255, pulse*120/255, pulse*160/255);
  uint16_t pinkCore = c565(pulse*220/255, pulse*35/255, pulse*105/255);
  uint16_t blueCore = c565(pulse*35/255, pulse*175/255, pulse*220/255);
  const uint8_t lx[5] = {6, 30, 54, 78, 102};
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  for (int i = 0; i < 5; i++) {
    if (i == 2 && (ms/1000)%2 == 0) continue;
    uint16_t mid = (i==2) ? blueGlow : pinkGlow;
    uint16_t core = (i==2) ? blueCore : pinkCore;
    uint16_t bright = (i==2) ? blue : pink;
    drawLargeFontChar(lx[i]-4, 2, buf[i], c565(pulse*50/255, pulse*8/255, pulse*20/255));
    drawLargeFontChar(lx[i]+4, 2, buf[i], c565(pulse*50/255, pulse*8/255, pulse*20/255));
    drawLargeFontChar(lx[i]-2, 2, buf[i], mid);
    drawLargeFontChar(lx[i]+2, 2, buf[i], mid);
    drawLargeFontChar(lx[i], 2, buf[i], core);
    drawLargeFontChar(lx[i], 2, buf[i], bright);
  }
}

// ── THEME 6: MATRIX ────────────────────────
// Large matrix-green digits with glitch effects
static void drawTheme_Matrix(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));
  const uint8_t lx[5] = {6, 30, 54, 78, 102};
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  for (int i = 0; i < 5; i++) {
    if (i == 2 && (ms/1000)%2 == 0) continue;
    drawLargeFontChar(lx[i]+2, 4, buf[i], c565(0,60,0));
    drawLargeFontChar(lx[i], 2, buf[i], c565(0,255,0));
  }
  for (int p = 0; p < 5; p++) {
    int sx = (p*31 + ms/30) % 108 + 10;
    int sy = (p*17 + ms/20) % 28 + 2;
    if ((ms/40 + p*10) % 7 < 3)
      display->drawPixel(sx, sy, c565(180,255,180));
  }
  for (int d = 0; d < 5; d++) {
    int rx = (d*23 + ms/60) % 100 + 14;
    int ry = (d*13 + ms/12) % 24 + 4;
    char rc = "0123456789ABCDEF"[(d*7 + ms/100) % 16];
    drawFontChar(rx, ry, rc, c565(0,100+(ry%3)*50,0));
  }
}

// ── THEME 7: FIRE ──────────────────────────
// Large fire digits with per-row flame coloring
static void drawTheme_Fire(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,0));
  const uint8_t lx[5] = {6, 30, 54, 78, 102};
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  for (int ci = 0; ci < 5; ci++) {
    if (ci == 2 && (ms/1000)%2 == 0) continue;
    int idx = -1;
    for (int i = 0; i < 11; i++) { if (font_chars[i] == buf[ci]) { idx = i; break; } }
    if (idx < 0) continue;
    uint8_t rows[7];
    memcpy_P(rows, font5x7[idx], 7);
    for (int row = 0; row < 7; row++) {
      for (int col = 0; col < 5; col++) {
        if (rows[row] & (0x10 >> col)) {
          int wobX = (sin8[(row*13+col*7+ci*30+ms/10)%256]-128)/64;
          int wobY = (sin8[(row*11+col*9+ci*40+ms/12)%256]-128)/64;
          int bx = lx[ci] + col*4 + wobX;
          int by = 2 + row*4 + wobY;
          int fl = (sin8[(row*31+col*17+ms/8)%256]+128)/10;
          uint8_t r,g,b;
          if (row >= 5) { r=255; g=180+fl; if(g>255)g=255; b=80+fl/2; if(b>255)b=255; }
          else if (row >= 3) { r=255; g=100+fl; b=fl/4; }
          else if (row >= 1) { r=180+fl; if(r>255)r=255; g=20+fl/5; b=0; }
          else { r=100+fl/3; g=5; b=0; }
          display->fillRect(bx, by, 4, 4, c565(r,g,b));
        }
      }
    }
  }
  for (int w = 0; w < 4; w++) {
    int wx = (w*31+ms/40)%108+10;
    int wy = 31-(ms/60+w*17)%28;
    int wh = 2+(w%3);
    for (int p = 0; p < wh; p++) {
      int t = (ms/25+w*41+p*60)%256;
      display->drawPixel(wx+p-1, wy-p, c565(255,100+t/4,0));
    }
  }
}

// ── THEME 8: RAINBOW ───────────────────────
// Large rainbow-cycling digits with sparkles
static void drawTheme_Rainbow(int h, int m, int s, unsigned long ms) {
  display->fillRect(0, 0, 128, 32, c565(0,0,15));
  const uint8_t lx[5] = {6, 30, 54, 78, 102};
  char buf[5];
  buf[0]='0'+h/10; buf[1]='0'+h%10; buf[2]=':'; buf[3]='0'+m/10; buf[4]='0'+m%10;
  for (int ci = 0; ci < 5; ci++) {
    if (ci == 2 && (ms/1000)%2 == 0) continue;
    int yOff = sin8[(ms/20 + ci*60) % 256] / 30;
    int idx = -1;
    for (int i = 0; i < 11; i++) { if (font_chars[i] == buf[ci]) { idx = i; break; } }
    if (idx < 0) continue;
    uint8_t rows[7];
    memcpy_P(rows, font5x7[idx], 7);
    for (int row = 0; row < 7; row++) {
      for (int col = 0; col < 5; col++) {
        if (rows[row] & (0x10 >> col)) {
          int bx = lx[ci] + col*4;
          int by = 2 + yOff + row*4;
          int hue = (ms/30 + ci*30 + row*20 + col*35) % 256;
          uint8_t r,g,b;
          int hp = hue % 85;
          if (hue < 85)       { r=255-hp*3; g=hp*3;   b=0; }
          else if (hue < 170) { r=0;        g=255-hp*3; b=hp*3; }
          else                { r=hp*3;     g=0;        b=255-hp*3; }
          display->fillRect(bx, by, 4, 4, c565(r,g,b));
        }
      }
    }
  }
  for (int s2 = 0; s2 < 6; s2++) {
    int sx = (s2*29 + ms/60) % 118 + 5;
    int sy = (s2*17 + ms/50) % 28 + 2;
    int sh = (ms/15 + s2*73) % 256;
    int h2 = sh % 85;
    uint8_t r,g,b;
    if (sh < 85)       { r=255-h2*3; g=h2*3;   b=0; }
    else if (sh < 170) { r=0;        g=255-h2*3; b=h2*3; }
    else               { r=h2*3;     g=0;        b=255-h2*3; }
    display->drawPixel(sx, sy, c565(r,g,b));
  }
}
// ── MAIN DISPATCHER ──────────────────────────────────────────
#define RETRO_THEME_COUNT 9

static void drawRetroClockTheme(int theme, int h, int m, int s, unsigned long ms) {
  switch (theme) {
    case 0: drawTheme_Mario(h, m, s, ms); break;
    case 1: drawTheme_Tetris(h, m, s, ms); break;
    case 2: drawTheme_Pacman(h, m, s, ms); break;
    case 3: drawTheme_Invaders(h, m, s, ms); break;
    case 4: drawTheme_Pong(h, m, s, ms); break;
    case 5: drawTheme_Neon(h, m, s, ms); break;
    case 6: drawTheme_Matrix(h, m, s, ms); break;
    case 7: drawTheme_Fire(h, m, s, ms); break;
    case 8: drawTheme_Rainbow(h, m, s, ms); break;
  }
}

static const char* retroThemeNames[RETRO_THEME_COUNT] = {
  "Super Mario", "Tetris", "Pac-Man",
  "Space Invaders", "Pong",
  "Neon", "Matrix", "Fire", "Rainbow"
};

#endif // CLOCK_THEMES_H
