# Retro Clock - Configuration
# Copie ce fichier a la racine de la carte SD

brightness=80                 	# Luminosite 0-100%

wifi_enabled=1               	# 0=OFF, 1=ON
wifi_ssid=VOTRE_SSID         	# Nom du reseau WiFi
wifi_password=VOTRE_MDP      	# Mot de passe WiFi

[CLOCK]
CLOCK_ENABLED=1              	# 0=OFF, 1=ON
CLOCK_THEME=-1               	# -1=random, 0=Mario, 1=Tetris, 2=Pac-Man
                                # 3=Space Invaders, 4=Game Boy, 5=Pokemon
                                # 6=Sonic, 7=Mega Man, 8=Pong
CLOCK_DURATION=10            	# secondes avant changement de theme (mode random)
CLOCK_INTERVAL_MIN=0         	# 0=affichage continu, >0 = minutes entre chaque affichage
TZ=CET-1CEST,M3.5.0,M10.5.0/3	# Fuseau horaire
