# ============================================================
# 🕹️ RETRO PIXEL LED LITE - ARCHIVO DE CONFIGURACION v2.1.0
# ============================================================
# Nota: No dejes espacios alrededor del símbolo '='.
# Ejemplo correcto: BRIGHTNESS=40

[WIFI_NTP]
# Configura tu red solo si vas a usar el reloj (CLOCK_ENABLE=1)
WIFI_ENABLE=1
SSID=Nombre_De_Tu_Red
PASS=Password_De_Tu_Red
TZ=CET-1CEST,M3.5.0,M10.5.0/3

[HARDWARE]
# Numero de paneles en cascada
PANEL_CHAIN=2
# Brillo general (0 a 255)
BRIGHTNESS=40
# Velocidad I2S: 0=8MHz, 1=10MHz, 2=16MHz, 3=20MHz (Turbo)
I2S_SPEED=2
# Refresco Minimo (Hz): 30 a 120
REFRESH_MIN=120
# Doble Buffer: 0=OFF, 1=ON (Elimina parpadeos)
DOUBLE_BUFF=1
# Anti-Ghosting: 1 a 4 (Sube si ves brillo fantasma)
LATCH_BLANK=1

[LOGIC]
# Modo de visualizacion: 0=GIFs, 1=Solo Reloj
PLAY_MODE=0
# Activa o desactiva el reloj: 0=OFF, 1=ON
CLOCK_ENABLE=1
# Modo de reproduccion: 0=Secuencial, 1=Aleatorio
RANDOM_MODE=1
# Intervalo: Cada cuantos GIFs aparece el reloj
AUTO_CLOCK_INT=6
# Duracion: Cuantos segundos se muestra el reloj
CLOCK_DURATION=10
# Estilos: 0=Matrix, 1=Solid, 2=Rainbow, 3=Pulse, 4=Gradient
CLOCK_STYLE=2
# Color del Reloj (Formato HEX)
CLOCK_COLOR=#FF0055

[WEATHER]
# Activa el clima: 0=OFF, 1=ON (Requiere WiFi)
WEATHER_ENABLE=1
# Tu ciudad (Sin espacios, usa '+' si es necesario: Madrid,ES o Buenos+Aires,AR)
CITY=Navalmoral+de+la+Mata,ES
# Tu API Key gratuita de OpenWeatherMap
API_KEY=xxxxxxxxxxxxxxxxxxxxxxx
# Intervalo de actualizacion en MINUTOS
WEATHER_INT=60
# Texto que se muestra encima del reloj
WEATHER_MSG=Game Room

[LANGUAGE]
# Indica el Idioma (Nombre del archivo sin .json: ES, EN, FR...)
LANGUAGE=ES
[END]
